spring.application.name=orderms
spring.data.mongodb.uri=mongodb://admin:123@localhost:27017/btgpactualdb?authSource=admin

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=123